### ISSUE TITLE
[BUG] Tracker for UI improvements

### ISSUE THREAD

**Issue by xiaoyongzhu** [feathr-ai/feathr#955]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Feathr version

0.9

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**:
- **Spark version, if reporting runtime issue**:

### Describe the problem

Tracker for UI improvements

### What component(s) does this bug affect?

- [ ] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by xiaoyongzhu** [comment]
1. We should also add place for users to create `Source` in pages

**Comment by xiaoyongzhu** [comment]
2. We should also jump to the corresponding projects after the feature is created

**Comment by xiaoyongzhu** [comment]
4. Seems this feature cannot be created successfully and there's no error message:
